<?php
globalvar_add_locale(array(
	'Activity' => 'กิจกรรม',
	'Activity Calendar' => 'ปฏิทินกิจกรรม',
	'Write new Activity entry' => 'เขียนกิจกรรมเพิ่ม',
	'Activity Configuration' => 'ปรับแต่งระบบของกิขกรรม',
	'icon size' => 'ขนาดไอคอน',
	'show avatar' => 'แสดงรูปอวตาล',
	'show category icon' => 'แสดงรูปหมวดหมู่',
	'show avatar for comments' => 'แสดงรูปอวตาลในความคิดเห็น',
	'user signature' => 'แสดงลายเซ็นผู้ใช้',
	'show in rendered activity' => 'แสดงผลในกิจกรรม',
	'icon' => 'ไอคอน',
	'activity start date' => 'วันเริ่มกิจกรรม',
	'activity end date' => 'วันจบกิจกรรม',
	'Calendar of Activities in this the Section.' => 'ปฏิทินกิจกรรมในเซคชั่น',
));
?>
