<?php
function requirement_get_expectation_option(){
	return array(
		0  => 'cool',
		1  => 'professional',
		2  => 'fresh',
		3  => 'happy',
		4  => 'modernism', 
		5  => 'light & comfort',
		6  => 'minimalism', 
		7  => 'healing',
		8  => 'natural',
		9  => 'monotone',
		10 => 'freak & fun',
		11 => 'mysterious & exotic',
		12 => 'retro',
		13 => 'sexy & trendy',
		14 => 'abstract method',
		15 => 'artistic',
		16 => 'hi-class',
		17 => 'colorful',
	);
}
?>
