<?php
globalvar_add_locale(array(
	'WREST' => 'เครือข่ายผู้หญิงพลิกโฉมประเทศไทย',
	'Meeting' => 'การประชุม',
	'Forum' => 'ระดมความเห็น',
	'News' => 'ข่าวเครือข่ายสตรี',
	'Article' => 'เรื่องน่าสนใจ',
	'news category' => 'หมวดหมู่ข่าว',
	'news number' => 'จำนวนข่าว',
	'article category' => 'หมวดหมู่เรื่องน่าสนใจ',
	'article number' => 'จำนวนเรื่องน่าสนใจ',
	'meeting number' => 'จำนวนการประชุม',
	'forum number' => 'จำนวนกระทู้',
	'words count' => 'จำนวนคำ',
	'Module for homepage of Women Network Reshaping Thailand (WREST).' => 'โมดูลหน้าแรกสำหรับเครือข่ายผู้หญิงพลิกโฉมประเทศไทย'
));
?>
