<?php
globalvar_add_locale(array(
	'place' => 'ส่วนราชการ',
	'document ID' => 'ที่',
	'write date' => 'วันที่',
	'topic' => 'เรื่อง',
	'prefix' => 'ส่ง/เสนอ/เรียน',
	'prefix I' => 'ส่ง',
	'prefix II' => 'เสนอ',
	'prefix III' => 'เรียน',
	'receiver' => 'ผู้รับ',
	'content' => 'ข้อความ',
	'rank of writer' => 'ยศผู้ลงชื่อ',
	'position of writer' => 'ตำแหน่งผู้ลงชื่อ',
	'signed by' => 'ลงชื่อ',
	'contributor' => 'ผู้เขียน',
	'created by' => 'โดย',
	'generate pdf' => 'สร้างเอกสาร pdf',
	'generate new document' => 'เขียนเอกสารฉบับใหม่'
));
?>
